services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: trabajoefs  
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - trabajoefs_data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d trabajoefs"] 
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: ..                      
      dockerfile: Api/Dockerfile 
    environment:
      ASPNETCORE_HTTP_PORTS: "8080"
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__Default: "Host=db;Port=5432;Database=trabajoefs;Username=postgres;Password=postgres"
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  trabajoefs_data:
